[package]
name = "little"
version = "0.1.0"
authors = ["Thomas-QM <thomas@engineeringvirtue.net>"]
edition = "2018"

[dependencies]
embedded-freetype-sys = "0.1.0"

[dev-dependencies]
glutin = "0.21.0"
gl = "0.12.0"